name: Deploy to Azure

on:
  push:
    branches:
      - main
      - 'feature/**'
  workflow_dispatch:

env:
  NODE_VERSION: '22'
  AZURE_RESOURCE_GROUP: rg-email-agent
  AZURE_LOCATION: eastus

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Functions dependencies
        run: |
          cd apps/functions
          npm ci

      - name: Build Functions
        run: |
          cd apps/functions
          npm run build

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Function App settings (worker indexing)
        run: |
          az functionapp config appsettings set \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings AzureWebJobsFeatureFlags=EnableWorkerIndexing

      - name: Restart Function App to apply settings
        run: |
          az functionapp restart \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
          package: apps/functions

  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: |
          npm run build
        env:
          VITE_FUNCTIONS_BASE_URL: ${{ secrets.AZURE_FUNCTION_APP_URL }}
          VITE_API_BASE: ${{ secrets.AZURE_FUNCTION_APP_URL }}

      - name: Deploy to Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"

  configure-cors:
    runs-on: ubuntu-latest
    needs: [deploy-functions, deploy-frontend]

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure CORS
        run: |
          # Get Static Web App URL
          SWA_URL=$(az staticwebapp show \
            --name ${{ secrets.AZURE_STATIC_WEB_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query "defaultHostname" -o tsv)

          # Add CORS origin to Function App
          az functionapp cors add \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --allowed-origins "https://$SWA_URL"

          echo "CORS configured for https://$SWA_URL"
