name: Deploy to Azure

on:
  push:
    branches:
      - main
      - 'feature/**'
  workflow_dispatch:

env:
  NODE_VERSION: '22'
  AZURE_RESOURCE_GROUP: rg-email-agent
  AZURE_LOCATION: eastus

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Functions dependencies
        run: |
          cd apps/functions
          npm ci

      - name: Build Functions
        run: |
          cd apps/functions
          npm run build

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Remove incompatible app settings for Flex Consumption
        run: |
          # Remove settings that are not supported by Flex Consumption SKU
          echo "Removing incompatible app settings..."
          az functionapp config appsettings delete \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --setting-names WEBSITE_RUN_FROM_PACKAGE SCM_DO_BUILD_DURING_DEPLOYMENT ENABLE_ORYX_BUILD || true

          echo "Incompatible settings removed (if they existed)"

      - name: Ensure Function App settings (Flex Consumption compatible)
        run: |
          # Flex Consumption plans manage most settings automatically
          # Only set EnableWorkerIndexing for function discovery
          az functionapp config appsettings set \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings \
              AzureWebJobsFeatureFlags=EnableWorkerIndexing

      - name: Restart Function App to apply settings
        run: |
          az functionapp restart \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

          # Wait for restart to complete
          echo "Waiting 30 seconds for function app to restart..."
          sleep 30

      - name: Package Functions app (zip)
        run: |
          cd apps/functions
          # Reduce node_modules to production only to keep the artifact lean
          npm prune --omit=dev || npm prune --production
          rm -f ../functions.zip
          # Zip only what the v4 worker needs: dist, node_modules, package.json, host.json
          zip -r ../functions.zip dist node_modules package.json host.json
          ls -lah ../functions.zip

      - name: Deploy Functions (config-zip primary, OneDeploy fallback)
        run: |
          set -e
          APP_NAME="${{ secrets.AZURE_FUNCTION_APP_NAME }}"
          RG="${{ env.AZURE_RESOURCE_GROUP }}"
          ZIP_PATH="apps/functions.zip"

          echo "Primary: az functionapp deployment source config-zip"
          DEPLOY_OK=0
          for attempt in 1 2 3; do
            echo "config-zip attempt #$attempt..."
            if az functionapp deployment source config-zip \
              --resource-group "$RG" \
              --name "$APP_NAME" \
              --src "$ZIP_PATH"; then
              DEPLOY_OK=1
              break
            fi
            echo "config-zip failed on attempt #$attempt. Retrying in 20s..."
            sleep 20
          done

          if [ "$DEPLOY_OK" -ne 1 ]; then
            echo "Fallback: az webapp deploy (OneDeploy)"
            for attempt in 1 2; do
              echo "OneDeploy attempt #$attempt..."
              if az webapp deploy \
                --resource-group "$RG" \
                --name "$APP_NAME" \
                --src-path "$ZIP_PATH" \
                --type zip; then
                DEPLOY_OK=1
                break
              fi
              echo "OneDeploy failed on attempt #$attempt. Retrying in 20s..."
              sleep 20
            done
          fi

          if [ "$DEPLOY_OK" -ne 1 ]; then
            echo "ERROR: Deploy failed after primary and fallback attempts"
            exit 1
          fi

      - name: Verify Functions discovered
        run: |
          echo "Waiting for functions to be indexed..."
          sleep 15

          echo "Listing discovered functions..."
          az functionapp function list \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} -o table

          CNT=$(az functionapp function list \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --query "length(@)")

          echo "Found $CNT functions"

          if [ "$CNT" -eq 0 ]; then
            echo "ERROR: 0 functions discovered after deployment"
            echo "Checking function app logs..."
            az functionapp log tail \
              --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --timeout 30 || true
            exit 1
          fi

          echo "✓ Successfully discovered $CNT functions"

      - name: Warm up function app
        run: |
          echo "Warming up function app by calling root URL..."
          FUNCTION_APP_URL="${{ secrets.AZURE_FUNCTION_APP_URL != '' && secrets.AZURE_FUNCTION_APP_URL || format('https://{0}.azurewebsites.net', secrets.AZURE_FUNCTION_APP_NAME) }}"

          # Try to call the root URL to warm up the app
          for i in 1 2 3; do
            echo "Warm-up attempt #$i..."
            curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" "$FUNCTION_APP_URL" || true
            sleep 5
          done

          echo "✓ Function app warm-up complete"

  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      FUNCTION_APP_URL: ${{ secrets.AZURE_FUNCTION_APP_URL != '' && secrets.AZURE_FUNCTION_APP_URL || format('https://{0}.azurewebsites.net', secrets.AZURE_FUNCTION_APP_NAME) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: |
          npm run build
        env:
          VITE_FUNCTIONS_BASE_URL: ${{ env.FUNCTION_APP_URL }}
          VITE_API_BASE: ${{ env.FUNCTION_APP_URL }}

      - name: Deploy to Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          output_location: ""
          skip_app_build: true

  configure-cors:
    runs-on: ubuntu-latest
    needs: [deploy-functions, deploy-frontend]

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure CORS
        run: |
          # Get Static Web App URL
          SWA_URL=$(az staticwebapp show \
            --name ${{ secrets.AZURE_STATIC_WEB_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query "defaultHostname" -o tsv)

          # Add allowed origins: SWA + local dev hosts
          ORIGINS=("https://$SWA_URL" "http://localhost:5175" "http://127.0.0.1:5175")

          for ORIGIN in "${ORIGINS[@]}"; do
            echo "Adding CORS origin: $ORIGIN"
            az functionapp cors add \
              --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --allowed-origins "$ORIGIN" || true
          done

          echo "CORS configured for: ${ORIGINS[*]}"

  test-endpoints:
    runs-on: ubuntu-latest
    needs: [deploy-functions, configure-cors]
    env:
      FUNCTION_APP_URL: ${{ secrets.AZURE_FUNCTION_APP_URL != '' && secrets.AZURE_FUNCTION_APP_URL || format('https://{0}.azurewebsites.net', secrets.AZURE_FUNCTION_APP_NAME) }}

    steps:
      - name: Test Azure Functions endpoints
        run: |
          set -e
          BASE_URL="${{ env.FUNCTION_APP_URL }}"
          echo "Testing endpoints at: $BASE_URL"

          # Test /api/nylas/unread (GET)
          echo "Testing GET /api/nylas/unread..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$BASE_URL/api/nylas/unread?limit=5")
          if [ "$STATUS" != "400" ] && [ "$STATUS" != "200" ]; then
            echo "ERROR: /api/nylas/unread returned $STATUS (expected 400 or 200)"
            exit 1
          fi
          echo "✓ /api/nylas/unread is accessible (status: $STATUS)"

          # Test /api/nylas/contacts (GET)
          echo "Testing GET /api/nylas/contacts..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$BASE_URL/api/nylas/contacts?limit=5")
          if [ "$STATUS" != "400" ] && [ "$STATUS" != "200" ]; then
            echo "ERROR: /api/nylas/contacts returned $STATUS (expected 400 or 200)"
            exit 1
          fi
          echo "✓ /api/nylas/contacts is accessible (status: $STATUS)"

          # Test /api/nylas/events (GET)
          echo "Testing GET /api/nylas/events..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$BASE_URL/api/nylas/events?limit=5")
          if [ "$STATUS" != "400" ] && [ "$STATUS" != "200" ]; then
            echo "ERROR: /api/nylas/events returned $STATUS (expected 400 or 200)"
            exit 1
          fi
          echo "✓ /api/nylas/events is accessible (status: $STATUS)"

          # Test /api/search (POST)
          echo "Testing POST /api/search..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d '{"queries":[{"text":"test"}],"top_k":5}' \
            "$BASE_URL/api/search")
          if [ "$STATUS" != "400" ] && [ "$STATUS" != "200" ] && [ "$STATUS" != "500" ]; then
            echo "ERROR: /api/search returned $STATUS (expected 400, 200, or 500)"
            exit 1
          fi
          echo "✓ /api/search is accessible (status: $STATUS)"

          # Test /api/aggregate (POST)
          echo "Testing POST /api/aggregate..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d '{"metric":"count","group_by":["from_domain"],"top_k":10}' \
            "$BASE_URL/api/aggregate")
          if [ "$STATUS" != "400" ] && [ "$STATUS" != "200" ] && [ "$STATUS" != "500" ]; then
            echo "ERROR: /api/aggregate returned $STATUS (expected 400, 200, or 500)"
            exit 1
          fi
          echo "✓ /api/aggregate is accessible (status: $STATUS)"

          # Test /api/realtime/session (POST)
          echo "Testing POST /api/realtime/session..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d '{}' \
            "$BASE_URL/api/realtime/session")
          if [ "$STATUS" != "400" ] && [ "$STATUS" != "200" ] && [ "$STATUS" != "500" ]; then
            echo "ERROR: /api/realtime/session returned $STATUS (expected 400, 200, or 500)"
            exit 1
          fi
          echo "✓ /api/realtime/session is accessible (status: $STATUS)"

          # Test /api/sync/delta (POST)
          echo "Testing POST /api/sync/delta..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d '{}' \
            "$BASE_URL/api/sync/delta")
          if [ "$STATUS" != "400" ] && [ "$STATUS" != "200" ]; then
            echo "ERROR: /api/sync/delta returned $STATUS (expected 400 or 200)"
            exit 1
          fi
          echo "✓ /api/sync/delta is accessible (status: $STATUS)"

          echo ""
          echo "✅ All endpoint tests passed!"
